//-----------------------------------------------------------------------------
#include "CException.h"
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
using namespace std;
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
CException::CException(const wstring& Value)
	: MValue(Value)
{
	wcout << L"CONSTRUCTOR [" << __func__ << L"()] CALLED !" << endl;
}
//-----------------------------------------------------------------------------
CException::~CException(void)
{
	wcout << L"DESTRUCTOR [" << __func__ << L"] CALLED !" << endl;
}
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
const wstring& CException::GetValue(void) const noexcept
{
	return(MValue);
}
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
wstring CException::GetTextMessage(void) const noexcept
{
	wstring														Message;

	Message.append(L"EXCEPTION [CException] - VALUE [");
	Message.append(MValue);
	Message.append(L"] !");

	return(Message);
}
//-----------------------------------------------------------------------------